//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app_im
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_inventario
    {
        public System.Guid id_inventario { get; set; }
        public string id_codigo_inventario { get; set; }
        public Nullable<int> id_grado_escolar { get; set; }
        public string categoria { get; set; }
        public string desc_inventario { get; set; }
        public string caracteristica { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> cantidad_minima { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> margen { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_centro { get; set; }
    }
}
