//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app_im
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_examenes_dep
    {
        public int id_examenes_desp { get; set; }
        public int id_pregunta_exam { get; set; }
        public int id_respuestas_exam { get; set; }
        public System.Guid id_examenes { get; set; }
    }
}
