//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app_im
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centro
    {
        public System.Guid id_centro { get; set; }
        public string id_codigo_centro { get; set; }
        public Nullable<int> id_tipo_centro { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public int id_licencia { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string cp { get; set; }
        public string calle { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> fecha_corte { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
