//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app_im
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_test_unam_dep
    {
        public int id_test_unam_dep { get; set; }
        public int id_pregunta { get; set; }
        public int id_respuestas_test { get; set; }
        public Nullable<System.Guid> id_usuario { get; set; }
    }
}
