//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app_im
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_preguntas_exam
    {
        public int id_pregunta_exam { get; set; }
        public string desc_pregunta_exam { get; set; }
        public int id_materia_exam { get; set; }
    }
}
